### ISSUE TITLE
Datastore queries for IN and NE

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-datastore#127] opened 2016-06-13 19:39 UTC
_From @ajagnanan on June 12, 2016 20:45_

Is there a timeline for when datastore will include IN and Not Equals filters? Or if it will be supported?

_Copied from original issue: GoogleCloudPlatform/gcloud-node#1376_

**Comment by stephenplusplus** [comment] 2016-06-13 19:39
// @pcostell 

Also, what is the ideal venue for questions like these?

**Comment by stephenplusplus** [comment] 2016-06-13 19:39
_From @pcostell on June 13, 2016 19:29_

You can redirect these to the google-cloud-datastore github project.

**Comment by pcostell** [comment] 2016-06-13 19:41
Duplicate of #36

**Closed** 2017-07-14 21:06 UTC
